<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.*,com.crm.model.WinLossReason,com.crm.model.Competitor,com.crm.controller.ServerForms" %>
<%!
 private String esc(Object v) { if (v==null) return ""; return String.valueOf(v).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;"); }
 private String selected(String current, String target) { return current.equals(target) ? " selected" : ""; }
%>
<%
 String tab=(String)request.getAttribute("tab"); if(tab==null)tab="WIN";
 boolean manage=Boolean.TRUE.equals(request.getAttribute("canManage"));
 List<WinLossReason> win=(List<WinLossReason>)request.getAttribute("winReasons");
 List<WinLossReason> loss=(List<WinLossReason>)request.getAttribute("lossReasons");
 List<Competitor> comps=(List<Competitor>)request.getAttribute("competitors");
 if(win==null)win=Collections.emptyList(); if(loss==null)loss=Collections.emptyList(); if(comps==null)comps=Collections.emptyList();
 String base=request.getContextPath()+"/winloss";
 String csrf=ServerForms.csrf(request);
 String error=(String)request.getAttribute("formError"); String flash=(String)request.getAttribute("flash");
%>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Danh mục thắng/thua và đối thủ</title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/shared/common.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/shared/layout.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/shared/header.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/shared/sidebar.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/shared/components.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/winloss/winloss.css">
<style>.wl-wrap{max-width:1180px;margin:24px auto;padding:12px}.wl-tabs{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}.wl-card{padding:20px;margin:18px 0;border:1px solid #cdd5dd;border-radius:8px}.wl-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.wl-grid label{display:block}.wl-grid input,.wl-grid select,.wl-grid textarea{width:100%;box-sizing:border-box;padding:8px}.wl-table{width:100%;border-collapse:collapse}.wl-table td,.wl-table th{padding:10px;text-align:left;border-bottom:1px solid #d5dce2}.wl-table-wrap{overflow:auto} .wl-notice{padding:12px;border:1px solid #adbac8;margin:12px 0} details{margin:12px 0}details summary{cursor:pointer;font-weight:bold}</style></head>
<body class="crm-body"><jsp:include page="/jsp/shared/header.jsp"/><div class="crm-main-layout"><jsp:include page="/jsp/shared/sidebar.jsp"/>
<main class="crm-page wl-wrap"><h1>Lý do thắng, lý do thua và đối thủ</h1>
<p>Quản lý các danh mục sử dụng khi đóng cơ hội bán hàng.</p>
<% if(error!=null){ %><div class="wl-notice" role="alert"><%=esc(error)%></div><% } %>
<% if(flash!=null){ %><div class="wl-notice" role="status"><%=esc(flash)%></div><% } %>
<nav class="wl-tabs" aria-label="Danh mục"><a href="<%=esc(base)%>?tab=WIN">Lý do thắng (<%=win.size()%>)</a><a href="<%=esc(base)%>?tab=LOSS">Lý do thua (<%=loss.size()%>)</a><a href="<%=esc(base)%>?tab=COMPETITOR">Đối thủ (<%=comps.size()%>)</a></nav>
<% if("COMPETITOR".equals(tab)){ %>
<section class="wl-card"><h2>Đối thủ cạnh tranh</h2><div class="wl-table-wrap"><table class="wl-table"><thead><tr><th>Thứ tự</th><th>Tên</th><th>Điểm mạnh</th><th>Điểm yếu</th><th>Website</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<% for(Competitor c:comps){ %><tr><td><%=c.getDisplayOrder()%></td><td><%=esc(c.getName())%></td><td><%=esc(c.getStrengths())%></td><td><%=esc(c.getWeaknesses())%></td><td><%=esc(c.getWebsite())%></td><td><%=c.isActive()?"Đang dùng":"Ngừng dùng"%></td><td>
<% if(manage){ %><details><summary>Sửa</summary><form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="COMPETITOR"><input type="hidden" name="operation" value="update"><input type="hidden" name="id" value="<%=c.getId()%>"><div class="wl-grid">
<label>Tên<input name="name" required maxlength="255" value="<%=esc(c.getName())%>"></label><label>Điểm mạnh<textarea name="strengths"><%=esc(c.getStrengths())%></textarea></label><label>Điểm yếu<textarea name="weaknesses"><%=esc(c.getWeaknesses())%></textarea></label><label>Website<input name="website" value="<%=esc(c.getWebsite())%>"></label><label>Thứ tự<input type="number" min="0" name="displayOrder" value="<%=c.getDisplayOrder()%>"></label><label>Trạng thái<select name="active"><option value="true"<%=selected(String.valueOf(c.isActive()),"true")%>>Đang dùng</option><option value="false"<%=selected(String.valueOf(c.isActive()),"false")%>>Ngừng dùng</option></select></label></div><button type="submit">Lưu thay đổi</button></form></details>
<form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="COMPETITOR"><input type="hidden" name="operation" value="delete"><input type="hidden" name="id" value="<%=c.getId()%>"><label><input type="checkbox" name="confirm" value="yes" required> Xác nhận thao tác</label><button type="submit">Xóa / Ngừng sử dụng</button></form><% } %></td></tr><% } %>
</tbody></table></div><% if(manage){ %><details class="wl-card"><summary>Thêm đối thủ</summary><form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="COMPETITOR"><input type="hidden" name="operation" value="create"><div class="wl-grid"><label>Tên<input required name="name" maxlength="255"></label><label>Điểm mạnh<textarea name="strengths"></textarea></label><label>Điểm yếu<textarea name="weaknesses"></textarea></label><label>Website<input name="website"></label><label>Thứ tự<input name="displayOrder" type="number" min="0" value="0"></label><label>Trạng thái<select name="active"><option value="true">Đang dùng</option><option value="false">Ngừng dùng</option></select></label></div><button type="submit">Thêm mới</button></form></details><% } %></section>
<% } else { List<WinLossReason> reasons="LOSS".equals(tab)?loss:win; %>
<section class="wl-card"><h2><%="WIN".equals(tab)?"Lý do thắng":"Lý do thua"%></h2><div class="wl-table-wrap"><table class="wl-table"><thead><tr><th>Thứ tự</th><th>Lý do</th><th>Mô tả</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<% for(WinLossReason r:reasons){ %><tr><td><%=r.getDisplayOrder()%></td><td><%=esc(r.getReasonText())%></td><td><%=esc(r.getDescription())%></td><td><%=r.isActive()?"Đang dùng":"Ngừng dùng"%></td><td><% if(manage){ %><details><summary>Sửa</summary><form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="<%=esc(tab)%>"><input type="hidden" name="operation" value="update"><input type="hidden" name="id" value="<%=r.getId()%>"><div class="wl-grid"><label>Lý do<input name="reasonText" required maxlength="255" value="<%=esc(r.getReasonText())%>"></label><label>Mô tả<textarea name="description"><%=esc(r.getDescription())%></textarea></label><label>Thứ tự<input type="number" name="displayOrder" min="0" value="<%=r.getDisplayOrder()%>"></label><label>Trạng thái<select name="active"><option value="true"<%=selected(String.valueOf(r.isActive()),"true")%>>Đang dùng</option><option value="false"<%=selected(String.valueOf(r.isActive()),"false")%>>Ngừng dùng</option></select></label></div><button type="submit">Lưu thay đổi</button></form></details><form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="<%=esc(tab)%>"><input type="hidden" name="operation" value="delete"><input type="hidden" name="id" value="<%=r.getId()%>"><label><input type="checkbox" name="confirm" value="yes" required> Xác nhận thao tác</label><button type="submit">Xóa / Ngừng sử dụng</button></form><% } %></td></tr><% } %>
</tbody></table></div><% if(manage){ %><details class="wl-card"><summary>Thêm lý do</summary><form action="<%=esc(base)%>" method="post"><input type="hidden" name="csrfToken" value="<%=esc(csrf)%>"><input type="hidden" name="tab" value="<%=esc(tab)%>"><input type="hidden" name="operation" value="create"><div class="wl-grid"><label>Lý do<input required name="reasonText" maxlength="255"></label><label>Mô tả<textarea name="description"></textarea></label><label>Thứ tự<input name="displayOrder" type="number" min="0" value="0"></label><label>Trạng thái<select name="active"><option value="true">Đang dùng</option><option value="false">Ngừng dùng</option></select></label></div><button type="submit">Thêm mới</button></form></details><% } %></section><% } %>
</main></div></body></html>
